# Generated by Django 3.1.3 on 2021-11-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gg01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gg03',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
    ]
