# Generated by Django 3.2.9 on 2021-11-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'managed': True},
        ),
    ]
