# Generated by Django 3.1.3 on 2021-11-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_gg02_gg04_gg05_gg06_gg07_gg08_gg09_gg10_gg11_gg12_gg13_gg14_gg15_gg16_gg17_gg18_gg19_gg20_gg21_gg22_'),
    ]

    operations = [
        migrations.CreateModel(
            name='gg25',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gg26',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gg27',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gg28',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('addr1', models.CharField(max_length=30)),
                ('addr2', models.CharField(max_length=30)),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
            ],
        ),
    ]
