# Generated by Django 3.2.9 on 2021-11-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_data_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
    ]
