# Generated by Django 3.2.9 on 2021-11-17 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='umd',
        ),
    ]
