# Generated by Django 3.2.9 on 2021-11-17 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_alter_address_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='district',
        ),
    ]
