# Generated by Django 3.2.9 on 2021-11-22 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'managed': False},
        ),
    ]
