# Generated by Django 3.1.3 on 2021-12-16 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20211207_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='address',
        ),
    ]
