from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(gg01)
admin.site.register(gg02)
admin.site.register(gg03)
admin.site.register(gg04)
admin.site.register(gg05)
admin.site.register(gg06)
admin.site.register(gg07)
admin.site.register(gg08)
admin.site.register(gg09)
admin.site.register(gg10)
admin.site.register(gg11)
admin.site.register(gg12)
admin.site.register(gg13)
admin.site.register(gg14)
admin.site.register(gg15)
admin.site.register(gg16)
admin.site.register(gg17)
admin.site.register(gg18)
admin.site.register(gg19)
admin.site.register(gg20)
admin.site.register(gg21)
admin.site.register(gg22)
admin.site.register(gg23)
admin.site.register(gg24)
admin.site.register(gg25)
admin.site.register(gg26)
admin.site.register(gg27)
admin.site.register(gg28)
